[project]
name = "cortana-sampler-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pydantic-settings>=2.2",
  "SQLAlchemy>=2.0",
  "redis>=5.0",
  "boto3>=1.34",
  "opencv-python-headless>=4.9",
]

[tool.uv]
dev-dependencies = []
