# .github/ISSUE_TEMPLATE/feature.yml
name: Feature Request
description: Create a new feature issue
title: "[Feature]: "
labels: ["type:feature"]
body:
    - type: markdown
      attributes:
          value: |
              ## Feature Request Template
              Fill out the sections below to help us understand your feature request.

    - type: dropdown
      id: service
      attributes:
          label: Service
          description: Which service does this feature affect?
          options:
              - api-gateway
              - s3-cron-scanner
              - transcode-worker
              - sampler-worker
              - ocr-worker
              - segment-index-worker
              - clip-service
              - frontend
              - infrastructure
              - documentation
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          options:
              - critical
              - high
              - medium
              - low
      validations:
          required: true

    - type: dropdown
      id: effort
      attributes:
          label: Estimated Effort
          options:
              - XS (1-2 hours)
              - S (3-8 hours)
              - M (1-3 days)
              - L (4-7 days)
              - XL (1-2 weeks)
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Description
          description: What feature do you want to implement?
          placeholder: Provide context and goals
      validations:
          required: true

    - type: textarea
      id: acceptance-criteria
      attributes:
          label: Acceptance Criteria
          description: List the requirements for this feature to be considered complete
          placeholder: |
              - [ ] Criterion 1
              - [ ] Criterion 2
              - [ ] Criterion 3
      validations:
          required: true

    - type: textarea
      id: technical-details
      attributes:
          label: Technical Details
          description: Technical requirements, APIs, dependencies
          placeholder: |
              **Tech Stack:**
              - Library X
              - Framework Y

              **Dependencies:**
              - Issue #123

              **Environment Variables:**
              ```
              VAR_NAME=value
              ```
      validations:
          required: false

    - type: textarea
      id: files
      attributes:
          label: Files to Create/Modify
          description: List files that will be affected
          placeholder: |
              - `services/api-gateway/src/cortana_api/main.py`
              - `deploy/prod/api-gateway/deployment.yaml`
      validations:
          required: false

---
# .github/ISSUE_TEMPLATE/bug.yml
name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["type:bug"]
body:
    - type: markdown
      attributes:
          value: |
              ## Bug Report Template
              Help us fix the issue by providing details below.

    - type: dropdown
      id: service
      attributes:
          label: Service
          description: Which service has the bug?
          options:
              - api-gateway
              - s3-cron-scanner
              - transcode-worker
              - sampler-worker
              - ocr-worker
              - segment-index-worker
              - clip-service
              - frontend
              - infrastructure
      validations:
          required: true

    - type: dropdown
      id: severity
      attributes:
          label: Severity
          options:
              - critical (system down)
              - high (major functionality broken)
              - medium (feature impaired)
              - low (minor issue)
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: What's the bug?
          placeholder: Clear description of the issue
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: Steps to Reproduce
          description: How can we reproduce this bug?
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. See error
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          description: What should happen?
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          description: What actually happens?
      validations:
          required: true

    - type: textarea
      id: logs
      attributes:
          label: Logs / Error Messages
          description: Paste relevant logs or error messages
          render: shell
      validations:
          required: false

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Where does this occur?
          placeholder: |
              - Environment: Production / Staging / Local
              - Service Version: v1.2.3
              - Kubernetes Version: 1.28
      validations:
          required: false

---

