[project]
name = "cortana-api-service"
version = "0.1.0"
description = "Upload gateway and job dispatcher for Cortana Vision"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic-settings",
    "python-multipart",
    "redis",
    "sqlalchemy",
    "aiosqlite",
    "boto3"
,]
